Fix a typo that causes an failure
>zvbi-0.2.44/src/ure.c:1355:19:
>error: ISO C23 does not allow arguments for function '_ure_make_expr' declared without parameters [-Werror=deprecated-non-prototype]
> 1355 |           state = _ure_make_expr(p, _ure_pop(b), state, b);
>
>zvbi-0.2.44/src/ure.c:1398:13:
>error: ISO C23 does not allow arguments for function '_ure_make_symbol' declared without parameters [-Werror=deprecated-non-prototype]
> 1398 |       sym = _ure_make_symbol(sp, ep - sp, &used, b);

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>